# Generated by Django 4.2.5 on 2023-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.BooleanField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
