# Generated by Django 4.2.5 on 2023-10-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
